### PR TITLE
Add lotico and loticoowl namespace

### PR DESCRIPTION
**Pull request by neumarcx**
Add lotico and loticoowl namespace to the Vocab module

### CODE REVIEW

**Comment by gkellogg** [comment]
@neumarcx doesn't look like the right branch/commit was used in this PR. Want to try again?

Remember to add an entry to the README.md for the vocabularies. Also, PR should go to the develop branch rather than master. Instructions are [in README](https://github.com/ruby-rdf/rdf-vocab#adding-new-vocabularies).

**Comment by bendiken** [comment]
@neumarcx You could also hop over to the chat room at https://gitter.im/ruby-rdf/rdf in case you need a hand on this.

**Comment by neumarcx** [comment]
thx, will do so next week


On Sun, Jun 21, 2015 at 1:42 PM, Arto Bendiken <notifications@github.com>
wrote:

> @neumarcx <https://github.com/neumarcx> You could also hop over to the
> chat room at https://gitter.im/ruby-rdf/rdf in case you need a hand on
> this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-rdf/rdf-vocab/pull/25#issuecomment-113934843>.
>



-- 


---
Marco Neumann
KONA

**Comment by gkellogg** [comment]
Thanks. This pull request has been integrated manually.

**Comment by gkellogg** [comment]
Finished PR, but don't see lotico or loticoowl vocabularies.

**Pull request closed without merging**
