### PR TITLE
Add the frozen_string_literal pragma

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by no-reply** [comment]
:+1: from me.

@gkellogg @bendiken we should talk about when and how to do this across the suite. See: https://bugs.ruby-lang.org/issues/11473

**Comment by jcoyne** [comment]
@no-reply here's how:
```
find . -name "*.rb" -exec perl -pi -e 'print "# frozen_string_literal: true\n" if $. == 1' {} \;
```

**Comment by bendiken** [comment]
Definitely a :+1: on this count.

**Comment by no-reply** [comment]
Well, I was all ready to merge, but `rbx` is failing:

`undefined method `[]' on nil:NilClass. (NoMethodError)`

**Comment by no-reply** [comment]
Looks like the rbx problem was just a CI hiccup.

**Comment by gkellogg** [comment]
Note that the generated vocabulary already freezes strings, so the `frozen_string_literal` pragma shouldn't cause anything else to freeze. We also can't get rid of the explicit `.frozen` method on each string because we need to be explicit for Ruby < 2.3.0, but it's certainly a reasonable thing to do, and we should, indeed, look to see where else it may be useful more generically.

**Comment by jcoyne** [comment]
@gkellogg not all strings were frozen. See the keys: https://github.com/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/dc.rb#L11-L13

**Comment by gkellogg** [comment]
True; those should probably be symbols, though. I'll look into that.

**Comment by no-reply** [comment]
This has me curious whether a symbol like `:'dc:creator'` instantiates a mutable string literal.

Life's Big Questions :tm:

**Comment by bendiken** [comment]
> This has me curious whether a symbol like `:'dc:creator'` instantiates a mutable string literal.

From a theoretical understanding that should just add a new entry to a symbol table. Each time you call `#to_s` on the `Symbol` object, it will give you back a newly-allocated `String` object. Obviously this is implementation-dependent, though.

**Comment by gkellogg** [comment]
Note that "foo-bar".to_sym #=> :"foo-bar"

**Pull request merged**
