### PR TITLE
Add EBUCore vocabulary

### PR DESCRIPTION
**Pull request by mjgiarlo**

### CODE REVIEW

**Comment by acoburn** [comment]
@mjgiarlo is there a special reason why the ebucore:hash property was renamed to ebucore:ebucore_hash?

**Comment by mjgiarlo** [comment]
@acoburn Ah!  I forgot about that -- maybe you can help me get past it.  vocab-fetch barfs, presumably because "hash" is a thing in Ruby:

```
/dir/to/rdf/lib/rdf/vocabulary.rb:294:in `has_key?': no implicit conversion of RDF::Vocabulary::Term into Integer (TypeError)
```

**Comment by acoburn** [comment]
@mjgiarlo did you also change the dc:alternative, dc:modified and dc:created to dcterms? (Those properties don't exist in dc11)

This is a problem with the ebucore vocabulary and I'd be more comfortable bringing this up with the publishers (and waiting for them to fix it). I'd be very hesitant to modify the content of an ontology just so it fits into a ruby expression of it.

**Comment by mjgiarlo** [comment]
@acoburn I just changed those too since they were causing tests to fail. I can ping the developers re: the three dc11 pointers and just use the working Ruby class in my own codebase for now.

The issue with "hash" is not a problem with the ontology, exactly, is it?

**Comment by acoburn** [comment]
@gkellogg would know why a property called `hash` causes errors

**Comment by gkellogg** [comment]
There are definitely times when errors in the base vocabulary need to be fixed s that consistence checks will pass. I don't think we can avoid this, but would be good to have an automated patch system so they don't need to be corrects manually. Definitely, the vocabulary maintainers should be encouraged to fix the original.

Regarding accessors, such as "hash", sometimes you can't use a Ruby method accessor, and need to use the index approach, such as EbuCore[:hash]. Not good to change core terms for convenience, although I could see a mechanism for providing aliases.

**Comment by mjgiarlo** [comment]
I've pinged the maintainers about the three dc/dc11 errors and the issue with "hash," in the meantime.

**Comment by mjgiarlo** [comment]
@gkellogg Assuming the ontology maintainers fix the DC-related errors and publish a new version, how do you recommend I proceed with the hash-related issue?  It makes vocab-fetch very :angry:.

**Comment by gkellogg** [comment]
@mjgiarlo, the problem was that Vocabulary created a property method for `hash`, which interfered with internal behavior on Object#hash. I added `hash` to `property` in the list of accessor methods that aren't created. Note, you'll need to do the vocab["hash"] access method.

**Comment by gkellogg** [comment]
@mjgiarlo To complete this merge, you'll need to re-generate using the updated vocab-loader in the develop branch of RDF.rb.

**Comment by mjgiarlo** [comment]
OK, in the meantime, the EBUCore maintainer wrote to say he's corrected the three DC/DCT-related issues and he's renamed "hash" to "hashCode" in the ontology.  I'll try regenerating this vocabulary and then I'll force-push to my branch.  Thanks, @gkellogg

**Comment by mjgiarlo** [comment]
Done. @gkellogg @acoburn

**Comment by bendiken** [comment]
> the EBUCore maintainer wrote to say he's corrected the three DC/DCT-related issues and he's renamed "hash" to "hashCode" in the ontology

Of course, [`java.lang.Object#hashCode()`](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()) is a core method in Java, so that may yet come back to bite him on other fronts... :wink:

**Comment by mjgiarlo** [comment]
What's Java?

;)

**Comment by gkellogg** [comment]
Looks like some new errors were introduced into the vocabulary, based on the Travis-CI failures.

**Comment by mjgiarlo** [comment]
Yes, indeed.  Just wrote about those errors.  Four of them are related to typos which should be easily correctable.  I'm not quite sure about the one related to "relation" in MA.  I see references to "relation" in the MA documentation but I'm not seeing it defined in RDF::Vocab::MA.  I'll make sure to run the test suite before pushing again, like I should have been doing already. :)

**Comment by mjgiarlo** [comment]
@acoburn @gkellogg OK, we're :green_heart:.

And @bendiken, the ontology has renamed `hashCode` to `hashValue` so there's that. :wink:

**Comment by gkellogg** [comment]
It looks like the vocabulary file still needs to be generated.

**Comment by gkellogg** [comment]
@mjgiarlo Once the new vocabulary file is generated, and tests pass, I can pull the changes and push an update.

**Comment by mjgiarlo** [comment]
@gkellogg This? https://github.com/ruby-rdf/rdf-vocab/pull/18/files#diff-0a20044de61b1efb8ce5c8eb0c5b6cad  Ths vocabulary file is there but GitHub isn't displaying it due to its size.

**Comment by mjgiarlo** [comment]
:clap: 

Thanks, @gkellogg

**Comment by gkellogg** [comment]
Released as version 0.8.3 of the gem. Thanks for the contributions!

**Comment by mjgiarlo** [comment]
Back at you.

**Pull request merged**
