### PR TITLE
Add RDA Vocabularies

### PR DESCRIPTION
**Pull request by lagoan**
http://www.rdaregistry.info/Elements/u/

### CODE REVIEW

**Review by lagoan — COMMENTED** [review]
I removed Alias information from the README.md file.

Will fix this in next commit.

**Comment by lagoan** [comment]
Alias information had been removed from upstream/develop. The current commit should be good to go.

**Comment by gkellogg** [comment]
Looks good, thanks! (In the future, please rebase rather than merge to develop).

It will be in the next release, which may not happen for a bit. Let me know if you have a critical dependency on getting it released sooner.

**Comment by lagoan** [comment]
Thank you very much for your prompt response. I will definitely rebase next
time!

We don't have a critical dependency and we may need to add more
vocabularies in the future so we can work around this for a bit.

Cheers,

Omar

+

**Pull request merged**
