### PR TITLE
added initial set of vocabularies

### PR DESCRIPTION
**Pull request by acoburn**
This adds an initial set of vocabularies to ruby-rdf/rdf-vocab

Unlike in projecthydra-labs/rdf-vocab, the PREMIS class does not have a V1 namespace (to make it consistent with everything else), the Fedora3 vocabulary was not included (there is no base RDF document for it), the IANA terms were not included (that is for another, separate PR)

Also, there is a somewhat more complete test suite.

The vocabularies here are not lazy-loaded (they should be).

/cc @mjgiarlo @jcoyne @dchandekstark @jpstroop

### CODE REVIEW

**Comment by dchandekstark** [comment]
@acoburn Thanks for doing all this work!  Basically I'm +1 on it.  My only question is about the whether vocabs should be in lib/rdf/vocab rather than lib/rdf-vocab/vocab.  I believe I used the the latter path in originally to avoid potential conflicts with RDF.rb or other libs that might put vocabs in the rdf/vocab require path.  Now that the project is being rebuilt here, maybe that should change?  @gkellogg

**Comment by bendiken** [comment]
@dchandekstark, right, the correct path (in keeping with RDF.rb gem conventions) would indeed be `lib/rdf/vocab`.

**Comment by gkellogg** [comment]
+1

**Comment by acoburn** [comment]
Great, I'll amend the PR to use `lib/rdf/vocab`

**Comment by gkellogg** [comment]
We may want some Rake tasks to rebuild the vocabulary list in the README from what is loaded. Also, there is traditionally an etc/doap.ttl file.

Don't worry about this stuff, I'll likely add to it.

BTW, if you're a committer, feel free to work on feature branches within the main repo; we can do pull requests from a feature to merge into develop, or trivial things can be done without a PR using git-flow on the client.

**Comment by acoburn** [comment]
there actually is a rake task to rebuild the vocab list:

    rake gen_vocabs

And yes, I thought I'd add the doap file later (but feel free to do it yourself)

**Comment by gkellogg** [comment]
Cool, thanks! I'll spend some time with this tomorrow.

**Comment by acoburn** [comment]
@gkellogg thanks -- we also need a Gemfile and related items. If I have time tonight, I'll add those (if not, I'll be on vacation for a week)

**Comment by gkellogg** [comment]
I'll take care of it tomorrow, if you don't get to it. Thanks again.

**Pull request merged**
